version: '3'

networks:
  guacamole_network:
    ipam:
      config:
        - subnet: 172.188.0.0/16

services:

  lighthouse:
    image: nebulaoss/nebula
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/nebula/common:/etc/nebula/common
      - ./config/nebula/lighthouse:/etc/nebula
      - ./config/nebula/lighthouse/config.lighthouse.yml:/config/config.yml
    networks:
      guacamole_network:
        ipv4_address: 172.188.0.2

  guacamole_mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guacamole_db
    volumes:
      - ./bin/mysql/start-mysql.sh:/docker-entrypoint-initdb.d/start-mysql.sh
      - ./dump/all-databases.sql:/docker-entrypoint-initdb.d/all-databases.sql
    networks:
      guacamole_network:
        ipv4_address: 172.188.0.3


  guacd:
    image: lziosi/guacd-nebula:0.0.6
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file:
      - ./config/guacd/nebula-config.list
    networks:
      guacamole_network:
        ipv4_address: 172.188.0.4

  guacamole:
    image: guacamole/guacamole
    ports:
      - 8080:8080
    environment:
      MYSQL_HOSTNAME: 172.188.0.3
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      GUACD_HOSTNAME: 172.188.0.4
    depends_on:
      - guacd
      - guacamole_mysql
    networks:
      guacamole_network:
        ipv4_address: 172.188.0.5

  rdphost:
    image: lziosi/rdphost-nebula:0.0.5
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./config/nebula/common:/etc/nebula/common
      - ./config/nebula/rdphost:/etc/nebula
    networks:
      guacamole_network:
        ipv4_address: 172.188.0.6

  rdphost2:
    image: lziosi/rdphost-nebula:0.0.5
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./config/nebula/common:/etc/nebula/common
      - ./config/nebula/rdphost2:/etc/nebula
    networks:
      guacamole_network:
        ipv4_address: 172.188.0.7

  sshhost:
    image: lziosi/sshhost-nebula:0.0.5
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./config/nebula/common:/etc/nebula/common
      - ./config/nebula/sshhost:/etc/nebula
    environment:
      - PASSWORD_ACCESS=true
      - USER_NAME=abc
      - USER_PASSWORD=abc
    networks:
      guacamole_network:
        ipv4_address: 172.188.0.9