FROM lscr.io/linuxserver/rdesktop:latest

COPY ./config/nebula/common /etc/nebula/common
COPY ./config/nebula/rdphost /etc/nebula
# Install build dependencies
RUN apk add --no-cache \
        nebula
		
CMD ["/usr/sbin/nebula", "-config", "/etc/nebula/config.rdphost.yml"]